Remove outdated LDAPS requirement
prestosql/presto pull request #4879
Opened 2020-08-18 20:19 UTC by dain

LDAPS is no longer required

2020-08-18 21:40 UTC, electrum commented on presto-docs/src/main/sphinx/security/ldap.rst
>  Environment Configuration
Remove this too, since this section is now empty

2020-08-18 21:40 UTC, electrum commented on presto-docs/src/main/sphinx/security/ldap.rst
> +``ldap.url``                                            The url to the LDAP server.
Uppercase URL. Maybe say
```
The URL scheme must be ``ldaps://`` or ``ldap://``.

2020-08-18 21:41 UTC, electrum commented on presto-docs/src/main/sphinx/security/ldap.rst
> +``ldap.allow-insecure``                                 If ``true`, non-ssl connections to the LDAP server are
Need two backticks

Capitalize SSL

Add period after second sentence

2020-08-20 22:42 UTC, electrum commented on presto-docs/src/main/sphinx/security/ldap.rst
>  Environment Configuration
You missed removing this

2020-08-25 09:03 UTC, kokosing commented
Please see https://github.com/prestosql/presto/pull/3644

2020-08-25 09:04 UTC, kokosing requested changes
Let's rebase this on top of: https://github.com/prestosql/presto/pull/3644

2020-09-17 17:19 UTC, closed without merging