Added new timezone configuration properties for the Hive connector.
prestosql/presto pull request #5004
Opened 2020-08-27 22:12 UTC by m57lyra

Adding in hive.*.time-zone configuration properties for parquet, orc, rcfile for release 341

Reviewer: @mosabua

2020-08-31 18:27 UTC, dain requested changes

2020-08-31 18:27 UTC, dain commented on presto-docs/src/main/sphinx/connector/hive.rst
> +``hive.orc.time-zone``                             Sets the default time zone for legacy ORC files that did
The default is also JVM default tz.

2020-08-31 18:27 UTC, dain commented on presto-docs/src/main/sphinx/connector/hive.rst
> +``hive.parquet.time-zone``                         Adjusts binary timestamp values to a specific time zone.     JVM default
I don't think "binary" here is significant as Parquet is always binary.

2020-08-31 18:27 UTC, dain commented on presto-docs/src/main/sphinx/connector/hive.rst
> +``hive.rcfile.time-zone``                          Adjusts binary timestamp values to a specific time zone.     JVM default
For here I think we want to say `binary encoded` since that is different from the default rc encoding which is text.

2020-09-01 05:45 UTC, m57lyra commented
<img width="871" alt="Screen Shot 2020-08-31 at 10 44 41 PM" src="https://user-images.githubusercontent.com/1664457/91799305-a2ce0f80-ebdb-11ea-957f-cba250be72d5.png">

2020-09-03 03:27 UTC, dain approved these changes

2020-09-03 03:28 UTC, merged