Add parse iso timestamp nanos
prestosql/presto pull request #5048
Opened 2020-09-01 15:02 UTC by alec-heif

2020-09-01 19:51 UTC, martint commented
@cla-bot check

2020-09-03 18:30 UTC, alec-heif commented
going to rebase this and try tests again since the failure seemed spurious

2020-09-03 23:01 UTC, alec-heif commented
Let me know if there's anything that needs to be done to include docs etc

2020-09-10 04:19 UTC, mosabua commented
Please add user documentation for the new function

2020-09-18 00:02 UTC, martint requested changes

2020-09-18 00:02 UTC, martint commented on presto-main/src/main/java/io/prestosql/operator/scalar/DateTimeFunctions.java
> +            return ((LocalDateTime) dt).atZone(ZoneId.of("UTC"));
This is inconsistent with the other variant (`from_iso8601_timestamp`), which uses session timezone if the timezone is missing from the input value.

2020-09-18 00:02 UTC, martint commented on presto-main/src/main/java/io/prestosql/operator/scalar/DateTimeFunctions.java
> +        TemporalAccessor dt;
Don't abbreviate variable names.

2020-09-18 00:02 UTC, martint commented on presto-main/src/main/java/io/prestosql/operator/scalar/DateTimeFunctions.java
> +        ZonedDateTime zdt = parseJavaDateTimeHelper(formatter, iso8601DateTime.toStringUtf8());
Don't abbreviate variable names

2020-09-18 00:02 UTC, martint commented on presto-main/src/main/java/io/prestosql/operator/scalar/DateTimeFunctions.java
> +        long picosOfSecond = zdt.getNano() * 1000L;
```suggestion
        long picosOfSecond = zdt.getNano() * PICOSECONDS_PER_NANOSECOND;
```

2020-09-18 00:02 UTC, martint commented on presto-main/src/test/java/io/prestosql/operator/scalar/TestDateTimeFunctions.java
> +    public void testFromISO8601Nanos()
```suggestion
    public void testFromIso8601Nanos()
```

2020-09-21 17:16 UTC, alec-heif commented on presto-main/src/main/java/io/prestosql/operator/scalar/DateTimeFunctions.java
> +    public static LongTimestampWithTimeZone fromISO8601TimestampNanos(ConnectorSession session, @SqlType("varchar(x)") Slice iso8601DateTime)
should I also change the other function above? since it's also called `fromISO8601Timestamp`

2020-09-21 17:19 UTC, martint commented on presto-main/src/main/java/io/prestosql/operator/scalar/DateTimeFunctions.java
> +    public static LongTimestampWithTimeZone fromISO8601TimestampNanos(ConnectorSession session, @SqlType("varchar(x)") Slice iso8601DateTime)
Yes, but let's do it in a separate commit, as it's cleanup of existing code.

2020-09-22 16:20 UTC, alec-heif commented
still need to add docs but otherwise I believe I've addressed all comments

2020-09-22 20:31 UTC, merged

2020-09-22 20:31 UTC, martint commented
I squashed the commits and merged it. Thanks!