Move benchmark driver doc into README
prestosql/presto pull request #5109
Opened 2020-09-08 23:13 UTC by m57lyra

Used pandocs to convert rst file
Added converted README.md file to presto-benchmark-driver
Removed rst file 
Removed mention of rst file in installation.rst

2020-09-08 23:32 UTC, mosabua commented
Looks like the md file renders ok in github 
https://github.com/m57lyra/presto/tree/benchmark-driver-readme/presto-benchmark-driver

2020-09-08 23:35 UTC, mosabua commented on presto-benchmark-driver/README.md
> +Download :maven_download:[benchmark-driver]{.title-ref}, rename it to
This definitely needs to be changed to be a valid URL.

2020-09-08 23:35 UTC, mosabua commented on presto-benchmark-driver/README.md
> +``` {.none}
We might need to change this table to be more markdownish as well

2020-09-16 23:11 UTC, mosabua commented on presto-benchmark-driver/README.md
> +=================
I am not sure this should be there .. is this not a remnant from the rst file?

2020-09-16 23:11 UTC, mosabua commented on presto-benchmark-driver/README.md
> +```
Please convert this into a markdown table instead of using a source code block.

2020-09-16 23:13 UTC, mosabua approved these changes
Everything moves over cleanly. Good job.

2020-09-16 23:13 UTC, mosabua commented
I am requesting review from @electrum to get this merged.

2020-09-16 23:14 UTC, mosabua commented
I also checked what the markdown renders in github and it looks good.

2020-09-16 23:17 UTC, mosabua requested changes
Download still needs to be fixed

2020-09-16 23:18 UTC, mosabua commented on presto-benchmark-driver/README.md
> + Download the [Maven benchmark driver plugin][maven_download] for the same
This needs to point to Central for download..

2020-09-16 23:19 UTC, mosabua commented on presto-benchmark-driver/README.md
> + Download the [Maven benchmark driver plugin][maven_download] for the same
https://repo.maven.apache.org/maven2/io/prestosql/presto-verifier/

2020-09-16 23:19 UTC, mosabua commented on presto-benchmark-driver/README.md
> + Download the [Maven benchmark driver plugin][maven_download] for the same
https://repo.maven.apache.org/maven2/io/prestosql/presto-benchmark-driver/

2020-10-01 17:38 UTC, electrum approved these changes

2020-10-01 17:43 UTC, merged