Add check for DISTINCT on non-aggregation function
prestosql/presto pull request #5418
Opened 2020-10-05 15:43 UTC by j4ckofalltrades

Fail with a proper analysis error with a more appropriate error message
rather than a generic VerifyException.

2020-10-05 17:11 UTC, martint requested changes

2020-10-05 17:11 UTC, martint commented on presto-main/src/main/java/io/prestosql/sql/analyzer/ExpressionAnalyzer.java
> +                throw semanticException(NOT_SUPPORTED, node, "DISTINCT is not supported for non-aggregation functions");
> `extractAggregateFunctions(List.of(node), metadata).isEmpty()`

This is not specific enough. For example, it won't catch `lower(DISTINCT max(a))`. It should directly check whether the function represented by this FunctionCall is DISTINCT and not an aggregation function.

Also, the check should be done only when the FunctionCall node is not a window function, as that check is handled elsewhere (e.g., `max(DISTINCT a) OVER ()`)

2020-10-06 00:56 UTC, j4ckofalltrades commented on presto-main/src/main/java/io/prestosql/sql/analyzer/ExpressionAnalyzer.java
> +                throw semanticException(NOT_SUPPORTED, node, "DISTINCT is not supported for non-aggregation functions");
Changes applied, thanks.

2020-10-06 03:07 UTC, martint commented
There are some build failures:

```
Error:  src/main/java/io/prestosql/sql/analyzer/ExpressionAnalyzer.java:[163,15] (imports) UnusedImports: Unused import - io.prestosql.sql.analyzer.ExpressionTreeUtils.extractAggregateFunctions.
Error:  src/main/java/io/prestosql/sql/analyzer/ExpressionAnalyzer.java:[947,13] (blocks) RightCurly: '}' at column 13 should be alone on a line.
```

2020-10-06 11:17 UTC, j4ckofalltrades commented
ci / pt (config-default, suite-6-non-generic) (pull_request) step failed with the following error (then stalled until timeout)?

```
2020-10-06T04:34:36.373Z	ERROR	container-stats-1	io.prestosql.tests.product.launcher.env.StatisticsFetcher	Could not fetch container hadoop-master statistics: java.lang.RuntimeException: java.lang.InterruptedException
```

2020-10-06 12:00 UTC, kokosing commented
Test failure seems to be related to: https://github.com/prestosql/presto/issues/5422

2020-10-07 12:17 UTC, j4ckofalltrades commented
Build checks pass now.

2020-10-08 16:08 UTC, martint commented
Merged, thanks!

2020-10-08 16:08 UTC, closed without merging

2020-10-09 11:42 UTC, j4ckofalltrades commented
@martint Looks like to forgot to merge? :)

2020-10-09 14:44 UTC, martint commented
No, i merged it directly after squashing the commits, but the github UI doesn’t show it: https://github.com/prestosql/presto/commit/b45c5741cb77012e5cf4d5fee34fe423e206e954

2020-10-09 14:58 UTC, j4ckofalltrades commented
Ahh cool, thanks.