Fix Launcher failure when suite remaining time is zero
prestosql/presto pull request #6020
Opened 2020-11-19 19:29 UTC by hashhar

`net.jodah.failsafe.Timeout.of()` only accepts values > 0 so we use the
smallest possible timeout to ensure we get a meaningful error

2020-11-19 20:34 UTC, wendigo approved these changes

2020-11-19 21:46 UTC, findepi requested changes
This should be handled in `io.prestosql.tests.product.launcher.cli.TestRun.Execution#call`, by refusing to work when `--timeout 0s` is passed.

2020-11-20 09:53 UTC, findepi commented on presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/TestRun.java
> +                log.error("Invalid timeout %s for test execution", timeout);
getting IAE here, can you be sure it's about timeout being incorrect?
better add an explicit check above
```
long timeoutMillis = timeout.toMillis();
if (timeoutMillis == 0) {
    log.eror("Invalid timeout or timeout exhausted");
    return ExitCode.SOFTWARE;
}

....
with(Timeout.of(java.time.Duration.ofMillis(timeoutMillis))
```

2020-11-20 11:14 UTC, findepi approved these changes

2020-11-20 11:14 UTC, merged