Compare compatible objects (int lists) in assertDynamicFiltering
prestosql/presto pull request #6267
Opened 2020-12-09 12:02 UTC by sopel39

2020-12-09 12:04 UTC, wendigo approved these changes

2020-12-09 15:48 UTC, losipiuk commented on presto-kudu/src/test/java/io/prestosql/plugin/kudu/TestKuduIntegrationDynamicFilter.java
> +import org.testng.internal.collections.Ints;
`org.testng.internal` ?

2020-12-09 15:56 UTC, losipiuk requested changes
I see that we use `org.testng.internal` in couple places. Would you have our own tool for converting int[] to List<Integer> and drop the use of internal package?

2020-12-09 16:15 UTC, sopel39 commented
@losipiuk it was meant to use `com.google.common.primitives.Ints;`

Thanks for catch!

2020-12-09 17:44 UTC, losipiuk commented
> @losipiuk it was meant to use `com.google.common.primitives.Ints;`
> 
> Thanks for catch!

Cool. Can you fix other occurrences and add modernizer rule to build?

2020-12-10 15:25 UTC, losipiuk approved these changes

2020-12-10 15:26 UTC, merged